
import React from 'react'
import s from './rashid.module.css'
import Link from 'next/link';

export const metadata = {
  title: 'Rashid',
  description: 'Generated by create next app',
}
export  async function getRashid() {
    const res = await fetch('https://jsonplaceholder.typicode.com/users');
    return res.json();
    
}

const Rashid = async () => {
  const data = await getRashid();

  return (
    <div style={{width: '100%' }} className='block-text'>
        <h1>Rashid</h1>
      {data.map((data)=>(
        <Link href={`/rashid/${data.id}`}> <div className={s.block} key={data.id}>
          <h3>{data.name}</h3>
          <p>{data.email}</p>
         
          </div></Link>
      ))}
     </div>
  )
}

export default Rashid